[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["gbslice <gerardburns@slicelife.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
mypy = "^1.15.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
